import type { Place } from "@/types/place";

// หมายเหตุ: lat/lng ในไฟล์นี้เป็นค่าโดยประมาณ ต้องตรวจกับ Google Maps ก่อน merge
// (คลิกขวาที่หมุดบน Google Maps แล้วคัดลอกพิกัด) และเรตติ้งของที่เพิ่มใหม่ (id 17-24) เป็นค่าชั่วคราว
export const places: Place[] = [
  {
    id: "1",
    name: "วัดพระธาตุดอยสุเทพ",
    category: "วัด / วัฒนธรรม",
    categoryId: "culture",
    rating: 4.8,
    image: "/images/places/doi-suthep.jpg",
    lat: 18.8048,
    lng: 98.9216,
    description:
      "วัดคู่บ้านคู่เมืองบนยอดดอยสุเทพ มีบันไดนาคและองค์พระธาตุสีทอง ชมวิวเมืองเชียงใหม่ได้จากลานด้านบน",
    trendingRank: 1,
    isRecommended: true,
  },
  {
    id: "2",
    name: "ดอยอินทนนท์",
    category: "ธรรมชาติ / ภูเขา",
    categoryId: "nature",
    rating: 4.8,
    image: "/images/places/doi-inthanon.jpg",
    lat: 18.5886,
    lng: 98.4865,
    description:
      "ยอดเขาที่สูงที่สุดในประเทศไทย อากาศเย็นตลอดปี มีป่าเมฆ น้ำตก และเจดีย์พระมหาธาตุนภเมทนีดลนภพลภูมิสิริ",
    trendingRank: 2,
    isRecommended: true,
  },
  {
    id: "3",
    name: "วัดพระสิงห์วรมหาวิหาร",
    category: "วัด / วัฒนธรรม",
    categoryId: "culture",
    rating: 4.7,
    image: "/images/places/wat-phra-singh.jpg",
    lat: 18.7882,
    lng: 98.9818,
    description:
      "วัดสำคัญในเขตคูเมือง เป็นที่ประดิษฐานพระพุทธสิหิงค์ และมีวิหารลายคำที่งดงามด้วยศิลปะล้านนา",
    isRecommended: true,
  },
  {
    id: "4",
    name: "วัดเจดีย์หลวงวรวิหาร",
    category: "วัด / โบราณสถาน",
    categoryId: "culture",
    rating: 4.7,
    image: "/images/places/wat-chedi-luang.jpg",
    lat: 18.7871,
    lng: 98.9868,
    description:
      "โบราณสถานกลางเมืองเก่า มีเจดีย์ทรงใหญ่สร้างตั้งแต่สมัยพญาแสนเมืองมา เคยเป็นที่ประดิษฐานพระแก้วมรกต",
    trendingRank: 5,
  },
  {
    id: "5",
    name: "วัดอุโมงค์สวนพุทธธรรม",
    category: "วัด / ธรรมชาติ",
    categoryId: "culture",
    rating: 4.6,
    image: "/images/places/wat-umong.jpg",
    lat: 18.7788,
    lng: 98.9546,
    description:
      "วัดป่าร่มรื่นที่มีอุโมงค์โบราณอายุหลายร้อยปี เหมาะกับการเดินเล่นและพักผ่อนท่ามกลางธรรมชาติ",
  },
  {
    id: "6",
    name: "น้ำตกห้วยแก้ว",
    category: "ธรรมชาติ / น้ำตก",
    categoryId: "nature",
    rating: 4.5,
    image: "/images/places/huay-kaew-waterfall.jpg",
    lat: 18.8118,
    lng: 98.9457,
    description:
      "น้ำตกขนาดเล็กใกล้ตัวเมือง อยู่ตีนดอยสุเทพ เดินทางสะดวก เหมาะกับการแวะพักก่อนขึ้นดอย",
    trendingRank: 3,
    isRecommended: true,
  },
  {
    id: "7",
    name: "ย่านนิมมานเหมินทร์",
    category: "คาเฟ่ / ช้อปปิ้ง",
    categoryId: "shopping",
    rating: 4.5,
    image: "/images/places/nimman.jpg",
    lat: 18.7996,
    lng: 98.968,
    description:
      "ย่านทันสมัยที่เต็มไปด้วยคาเฟ่ ร้านขายของแต่งบ้าน แกลเลอรี และร้านอาหาร เดินเล่นได้ทั้งวัน",
    trendingRank: 4,
  },
  {
    id: "8",
    name: "ประตูท่าแพ",
    category: "สถานที่ท่องเที่ยว / ประตูเมืองเก่า",
    categoryId: "culture",
    rating: 4.5,
    image: "/images/places/tha-phae-gate.jpg",
    lat: 18.7878,
    lng: 99.0003,
    description:
      "ประตูเมืองด้านตะวันออกของคูเมืองเชียงใหม่ จุดถ่ายรูปยอดนิยม และเป็นจุดเริ่มต้นของถนนคนเดินวันอาทิตย์",
    isRecommended: true,
  },
  {
    id: "9",
    name: "น้ำตกบัวตอง (น้ำตกน้ำพุเจ้าชาย)",
    category: "ธรรมชาติ / น้ำตก",
    categoryId: "nature",
    rating: 4.6,
    image: "/images/places/bua-thong.jpg",
    lat: 19.0528,
    lng: 98.9331,
    description:
      "น้ำตกหินปูนที่เดินขึ้นได้โดยไม่ลื่น เพราะผิวหินมีหินปูนเกาะ น้ำใสและเย็น เหมาะกับครอบครัว",
    trendingRank: 6,
  },
  {
    id: "10",
    name: "Elephant Nature Park",
    category: "กิจกรรม / สัตว์",
    categoryId: "nature",
    rating: 4.8,
    image: "/images/places/elephant-nature-park.jpg",
    lat: 19.3626,
    lng: 98.8903,
    description:
      "ศูนย์ดูแลและฟื้นฟูช้างที่ได้รับการช่วยเหลือ ผู้มาเยือนได้ใกล้ชิดช้างในธรรมชาติโดยไม่มีการขี่หรือแสดง",
    isRecommended: true,
  },
  {
    id: "11",
    name: "ม่อนแจ่ม",
    category: "ธรรมชาติ / จุดชมวิว",
    categoryId: "nature",
    rating: 4.6,
    image: "/images/places/mon-cham.jpg",
    lat: 18.92,
    lng: 98.818,
    description:
      "จุดชมวิวบนดอยอากาศเย็น มีทะเลหมอกและไร่ดอกไม้ตามฤดูกาล และมีที่พักและร้านกาแฟให้นั่งพัก",
    isRecommended: true,
  },
  {
    id: "12",
    name: "เมญ่า (MAYA)",
    category: "ช้อปปิ้ง / ห้างสรรพสินค้า",
    categoryId: "shopping",
    rating: 4.5,
    image: "/images/places/maya-chiang-mai.jpg",
    lat: 18.8021,
    lng: 98.9674,
    description:
      "ห้างสรรพสินค้าใจกลางย่านนิมมาน มีร้านค้า ร้านอาหาร โรงภาพยนตร์ และดาดฟ้าที่ชมวิวดอยสุเทพได้",
    isRecommended: true,
  },
  {
    id: "13",
    name: "บ้านแม่กำปอง",
    category: "ธรรมชาติ / หมู่บ้านบนเขา",
    categoryId: "nature",
    rating: 4.6,
    image: "/images/places/ban-mae-kampong.jpg",
    lat: 18.8606,
    lng: 99.3306,
    description:
      "หมู่บ้านบนเขาที่เงียบสงบ ล้อมรอบด้วยป่าและสายหมอก มีน้ำตกและโฮมสเตย์ให้พักผ่อนแบบชุมชน",
  },
  {
    id: "14",
    name: "ตลาดวโรรส (กาดหลวง)",
    category: "ตลาด / ของฝาก",
    categoryId: "shopping",
    rating: 4.4,
    image: "/images/places/warorot-market.jpg",
    lat: 18.7899,
    lng: 98.9995,
    description:
      "ตลาดเก่าแก่ที่ขายของฝากพื้นเมือง ทั้งไส้อั่ว แคบหมู น้ำพริกหนุ่ม และผ้าทอ เหมาะกับการซื้อของกลับบ้าน",
  },
  {
    id: "15",
    name: "บ้านค่างวัด (Baan Kang Wat)",
    category: "คาเฟ่ / ศิลปะ",
    categoryId: "art",
    rating: 4.5,
    image: "/images/places/baan-kang-wat.jpg",
    lat: 18.7775,
    lng: 98.9535,
    description:
      "ชุมชนศิลปินใกล้วัดอุโมงค์ มีสตูดิโอ ร้านงานฝีมือ และคาเฟ่เล็ก ๆ ในบรรยากาศร่มรื่น",
  },
  {
    id: "16",
    name: "เชียงใหม่ไนท์ซาฟารี",
    category: "กิจกรรม / ท่องเที่ยวกลางคืน",
    categoryId: "nature",
    rating: 4.4,
    image: "/images/places/chiang-mai-night-safari.jpg",
    lat: 18.739,
    lng: 98.919,
    description:
      "สวนสัตว์กลางคืนที่นั่งรถรางชมสัตว์ในเวลากลางคืน มีโซนเดินชมและการแสดงให้ดูตลอดทั้งคืน",
  },
  {
    id: "17",
    name: "อ่างแก้ว มหาวิทยาลัยเชียงใหม่",
    category: "ธรรมชาติ / จุดพักผ่อน",
    categoryId: "nature",
    rating: 4.7,
    image: "/images/places/ang-kaew.jpg",
    lat: 18.8062,
    lng: 98.9534,
    description:
      "อ่างเก็บน้ำภายใน มช. บรรยากาศร่มรื่น มองเห็นวิวดอยสุเทพสะท้อนน้ำ เป็นจุดพักผ่อน รับลม และชมพระอาทิตย์ตกยอดนิยม",
  },
  {
    id: "18",
    name: "ถนนคนเดินท่าแพ (วันอาทิตย์)",
    category: "ตลาดกลางคืน / ถนนคนเดิน",
    categoryId: "nightmarket",
    rating: 4.6,
    image: "/images/places/sunday-walking-street.jpg",
    lat: 18.788,
    lng: 98.988,
    description:
      "ถนนคนเดินกลางเมืองเก่าเฉพาะวันอาทิตย์ ยาวจากประตูท่าแพถึงวัดพระสิงห์ เต็มไปด้วยงานฝีมือและของกิน",
  },
  {
    id: "19",
    name: "ไนท์บาซาร์เชียงใหม่",
    category: "ตลาดกลางคืน / ช้อปปิ้ง",
    categoryId: "nightmarket",
    rating: 4.3,
    image: "/images/places/night-bazaar.jpg",
    lat: 18.7859,
    lng: 99.0027,
    description:
      "ตลาดกลางคืนเปิดทุกวัน ขายของฝาก เสื้อผ้า และสินค้าแฮนด์เมด มีโซนอาหารและร้านนั่งชิลล์รอบ ๆ",
  },
  {
    id: "20",
    name: "สวนพฤกษศาสตร์สมเด็จพระนางเจ้าสิริกิติ์",
    category: "ธรรมชาติ / สวนพฤกษศาสตร์",
    categoryId: "nature",
    rating: 4.6,
    image: "/images/places/queen-sirikit-botanic-garden.jpg",
    lat: 18.8989,
    lng: 98.8604,
    description:
      "ศูนย์รวบรวมพรรณไม้ระดับสากล อ.แม่ริม มี Canopy Walkway เดินชมธรรมชาติเหนือยอดไม้ และกลุ่มเรือนกระจกแสดงพืชพรรณต่างๆ",
  },
  {
    id: "21",
    name: "ข้าวซอยเสมอใจ",
    category: "ของกิน / อาหารเหนือ",
    categoryId: "food",
    rating: 4.4,
    image: "/images/places/khao-soi-samer-jai.jpg",
    lat: 18.7948,
    lng: 98.9972,
    description:
      "ร้านข้าวซอยและอาหารเหนือที่เปิดมานาน ราคาย่อมเยา เหมาะกับมื้อกลางวันหลังเดินชมเมืองเก่า",
  },
  {
    id: "22",
    name: "เฮือนเพ็ญ",
    category: "ของกิน / อาหารล้านนา",
    categoryId: "food",
    rating: 4.4,
    image: "/images/places/huen-phen.jpg",
    lat: 18.787,
    lng: 98.987,
    description:
      "ร้านอาหารล้านนาในบ้านไม้เก่า ใกล้วัดเจดีย์หลวง เสิร์ฟแกงฮังเล น้ำพริกหนุ่ม และไส้อั่ว",
  },
  {
    id: "23",
    name: "พิพิธภัณฑ์ศิลปะร่วมสมัยไม้แอม (MAIIAM)",
    category: "ศิลปะ / พิพิธภัณฑ์",
    categoryId: "art",
    rating: 4.5,
    image: "/images/places/maiiam.jpg",
    lat: 18.7543,
    lng: 99.0384,
    description:
      "พิพิธภัณฑ์ศิลปะร่วมสมัยที่จัดแสดงผลงานศิลปินไทยและนานาชาติ ตัวอาคารมีสถาปัตยกรรมโดดเด่น",
  },
  {
    id: "24",
    name: "หมู่บ้านทำร่มบ่อสร้าง",
    category: "ศิลปะ / หัตถกรรมชุมชน",
    categoryId: "art",
    rating: 4.3,
    image: "/images/places/bo-sang.jpg",
    lat: 18.77,
    lng: 99.063,
    description:
      "หมู่บ้านหัตถกรรมที่ทำร่มกระดาษสาและร่มผ้าด้วยมือ ชมขั้นตอนการทำและเลือกซื้อของฝากจากช่างโดยตรง",
  },
];
